### ISSUE TITLE
[REQUEST] FLUXION

### ISSUE THREAD

**Issue by deltaxflux** [ApatheticEuphoria/WPS-SLAUGHTER#1]
I have created a Auto WIFI Cracker called Fluxion. All in all there is more than 4500 lines of code. So my idea is that we put our project together because we will get a higher ranking and can remove bugs easier. However if you interested in, you can check out my project 

https://github.com/deltaxflux/flux

**Comment by ApatheticEuphoria** [comment]
You can add my script to the flux folder,and use with Flux like from the menu or something. But Keep in mind the target scanner is buggy right now.* As for putting our projects together. Not entirely sure how you mean,do you have a skype i can contact you on? Also i cant get flux to work right on kali 2.0 says no wifi card but there is one...

**Comment by deltaxflux** [comment]
can u send me your skype id i will add u, flux is for older aircrack-ng versions so i have created a page to solve this problem you can find this in the kali folder

**Comment by ApatheticEuphoria** [comment]
apathetic_euphoria

**Comment by aanarchyy** [comment]
I may be willing to help as well if you wish :-)

**Comment by deltaxflux** [comment]
Instructions:
1) Download Flux 
2) CD flux-master
3) CD kali
4). /fluxion
I add your wps Script 
Change  something 
Look at fluxion

**Comment by ApatheticEuphoria** [comment]
I'll update sometime today and check it out.

**Comment by deltaxflux** [comment]
whats your skype id , im lazy :)

**Comment by ApatheticEuphoria** [comment]
apathetic_euphoria
